// import './_aos.js';
import './_choices.js';
// import './_elipsis.js';
// import './_inputmask.js';
// import './_isotope.js';
import './_just-validate.js';
import './_mixitup.js';
import './_modals.js';
// import './_nouislider.js';
// import './_tabs.js';
// import './_tippy.js';
// import './_tippy.js';
